# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f23d8a0db00c79c36e3edb36ab4e9773754b34c70db73c5a04bb50c8dc4446dceb048d2e69f77beb545af52cbe222f5eea6be2a8b7fd474952909c402d0445ba

test:
  secret_key_base: 8813633e3b548049f9f9b4ef7fcd89452de2006af3665cbb6b8e83d5e40e42db371a596bd4676bbbe91eac99cbbb4b817907dbc5765c85eb35d8325d309f53c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
